---
- name: create docker-services directory
  become_user: "{{login_user}}"
  file:
    path: "/home/{{login_user}}/docker-services"
    mode: "0755"
    state: directory
- name: create docker-services registry directory
  become_user: "{{login_user}}"
  file:
    path: "/home/{{login_user}}/docker-services/{{item}}"
    mode: "0755"
    state: directory
  loop:
    - "vps"
- name: copy docker files to host yml
  become_user: "{{login_user}}"
  copy:
    force: yes
    src: "{{inventory_dir}}/files/{{item.src}}"
    dest: "/home/{{login_user}}/docker-services/vps/{{item.dest}}"
  loop:
    - { src: "docker/Dockerfile.vps", dest: "Dockerfile" }
    - { src: "sshd/sshd_config", dest: "sshd_config" }
    - { src: "fail2ban/fail2ban.conf", dest: "fail2ban.conf" }
- name: confirm we have ssh keys
  ansible.builtin.assert:
    that:
      - "'{{ machine_ssh_pub }}' != ''"
      - "'{{ host_ssh_pub }}' != ''"
- name: Build docker image using vps dockerfile
  shell: "docker build --build-arg \"USER_SSH_PUB_KEY={{ machine_ssh_pub}}\" --build-arg \"USER_SSH_PUB_KEY2={{host_ssh_pub}}\" -t machine_image:{{ vps_image_version }} -f /home/{{login_user}}/docker-services/vps/Dockerfile /home/{{login_user}}/docker-services/vps"
- name: Tag docker image using local docker registry
  shell: "docker tag machine_image:{{ vps_image_version }} localhost:5443/machine_image:{{ vps_image_version }}"
- name: Push docker image to local docker registry
  shell: "docker push localhost:5443/machine_image:{{ vps_image_version }}"
